export const kingnom = [
    'Karas',
    'Cuisine',
    'Coffeeshop',
    'Shaurma',
    'Grill',
    'Pizza',
    'Caucasus',
    'choice',
    'Grilled',
    'Soup',
    'Pideh',
    'Sweet',
    'Ground',
    'Hamburger',
    'Lunchy',
    'Edamame',
    'Breakfast',
    'Avokado',
    'Baguette',
    'Dargett',
    'Muchacho',
    'Ikigai',
    'Makarone',
    'Chaihona',
    'Zhengyalov Hats']