export const bestitem = [
    {
        id: 173,
        src: "https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic8.webp",
        name: 'Baby slippers',
        text: 'Rating and reviews will be seen after login  Parturient metus sollicitudin cras dis facilisi venenatis urna tempus placerat neque vestibulum auctor interdum leo litora dolor ullamcorper dignissim nisl pharetra suscipit amet vulputate si orci',
        price: '11.00 – $16.00',
        age: ['Choose an option','0-1', '1-2', '2-3'],
    },
    {
        id: 174,
        src: 'https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic3.webp',
        name: 'Baby Socks',
        text: 'Rating and reviews will be seen after login  Curabitur duis magnis conubia nec potenti blandit malesuada ligula id cras dui mauris tellus faucibus morbi natoque dictum amet convallis ante',
        price: '15.00 – $19.00',
        age: ['Choose an option','0-1', '1-2', '2-3'],
    },
    {
        id: 175,
        src: 'https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic1.webp',
        name: 'Bear boots',
        text: 'Rating and reviews will be seen after login  Imperdiet egestas sagittis proin euismod magnis pretium lacinia facilisis etiam ex litora consectetur lectus si condimentum felis torquent risus at ac integer per',
        price: '25.00 – $28.00',
        age: ['Choose an option','0-1', '1-2', '2-3', '3-4'],
    },
    {
        id: 176,
        src: 'https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic6.webp',
        name: 'Cardigan longsleeve',
        text: 'Rating and reviews will be seen after login  Vehicula quisque mollis senectus sit viverra si fames molestie nibh dui ultrices quis sodales orci mi turpis neque aptent et felis vitae at pretium vestibulum malesuada nisl himenaeos',
        price: '66.00',
        age: ['Choose an option','0-1', '1-2', '2-3'],
    },
    {
        id: 177,
        src: 'https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic9.webp',
        name: 'Girl blouse',
        text: 'Rating and reviews will be seen after login Aptent penatibus dolor netus vulputate convallis egestas rutrum non sodales bibendum torquent mattis nostra curae nascetur felis conubia mauris congue enim fringilla pulvinar sem vivamus lectus',
        price: '38.00 – $46.00',
        age: ['Choose an option','0-1', '1-2', '2-3'],
    },
    {
        id: 178,
        src: 'https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic4.webp',
        name: 'Love Blouse',
        text: 'Rating and reviews will be seen after login  Orci interdum nec placerat dapibus aliquet massa pharetra laoreet mi mattis neque augue cursus nam et vestibulum facilisis platea tellus',
        price: '32.00 – $38.00',
        age: ['Choose an option', '62/68 cm', '74/80cm', '86/92cm', '94/108cm', '110/116cm'],
    },
    {
        id: 179,
        src: 'https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic2.webp',
        name: 'Sleeveless Cardigan',
        text: 'Rating and reviews will be seen after login   Curae donec amet duis euismod nisl etiam mus proin a fames praesent orci tortor non vel',
        price: '115.00 – $122.00',
        age: ['Choose an option','0-1', '1-2', '2-3'],
    },
    {
        id: 180,
        src: 'https://themes.muffingroup.com/be/babyshop2/wp-content/uploads/2023/11/babyshop2-product-pic5.webp',
        name: 'Sweater',
        text: 'Rating and reviews will be seen after login  Curabitur duis magnis conubia nec potenti blandit malesuada ligula id cras dui mauris tellus faucibus morbi natoque dictum amet convallis ante',
        price: '142.00 – $150.00',
        age: ['Choose an option', '62/68 cm', '74/80cm', '86/92cm', '94/108cm', '110/116cm'],
    }
]